name: Sheet to Json

on:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i
      - run: npm start
      - name: Commit New Data
        run: |
          git config --global user.name 'nkadebug'
          git config --global user.email 'nkadebug@users.noreply.github.com'
          git add .
          set +e  # Grep succeeds with nonzero exit codes to show results.
          if git status | grep 'new file\|modified'
          then
            set -e
            git commit -am "Sheet to JSON - updated on - $(date)"
            git push
            echo "Pushed new files"
          else
            set -e
            echo "No changes since last run"
          fi
